"""Mô tả thay đổi

Revision ID: 78de60471fc3
Revises: 
Create Date: 2024-10-11 13:26:26.948927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78de60471fc3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'title',
               existing_type=sa.VARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('todos', 'description',
               existing_type=sa.VARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('todos', 'priority',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.create_index(op.f('ix_todos_id'), 'todos', ['id'], unique=False)
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=45, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=45, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=45, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=45, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'role',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=45, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('users', 'last_name',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=45, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('users', 'first_name',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=45, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('users', 'username',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=45, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('users', 'email',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.drop_column('users', 'phone_number')
    op.drop_index(op.f('ix_todos_id'), table_name='todos')
    op.alter_column('todos', 'priority',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('todos', 'description',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('todos', 'title',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    # ### end Alembic commands ###
